# Generated by Django 5.2.17 on 2026-08-22 05:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='storyreaction',
            index=models.Index(fields=['story', 'user'], name='stories_sto_story_i_a09593_idx'),
        ),
        migrations.AddConstraint(
            model_name='storyreaction',
            constraint=models.UniqueConstraint(fields=('story', 'user', 'reaction'), name='unique_story_user_reaction'),
        ),
    ]
