# Generated by Django 5.2.17 on 2026-08-22 03:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0001_initial'),
        ('posts', '0002_bookmark_postreaction_usertag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostCollaboration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending Collaboration Invite'), ('accepted', 'Accepted — Co-Creator'), ('rejected', 'Rejected'), ('revoked', 'Revoked')], db_index=True, default='pending', max_length=20)),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='communities.community'),
        ),
        migrations.AddField(
            model_name='post',
            name='content_warning',
            field=models.CharField(choices=[('none', 'No Warning'), ('sensitive', 'Sensitive Content'), ('spoiler', 'Spoiler Warning'), ('mature', 'Mature Content'), ('graphic', 'Graphic Content'), ('disturbing', 'Potentially Disturbing')], db_index=True, default='none', max_length=20),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['community', '-created_at'], name='posts_post_communi_ddf459_idx'),
        ),
        migrations.AddField(
            model_name='postcollaboration',
            name='collaborator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborative_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postcollaboration',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborations', to='posts.post'),
        ),
        migrations.AddConstraint(
            model_name='postcollaboration',
            constraint=models.UniqueConstraint(fields=('post', 'collaborator'), name='unique_post_collaborator'),
        ),
    ]
