# Generated by Django 5.2.17 on 2026-08-22 02:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPrivacySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_private', models.BooleanField(default=False)),
                ('who_can_message', models.CharField(choices=[('everyone', 'Everyone'), ('followers', 'Followers Only'), ('nobody', 'Nobody')], default='everyone', max_length=20)),
                ('who_can_mention', models.CharField(choices=[('everyone', 'Everyone'), ('followers', 'Followers Only'), ('nobody', 'Nobody')], default='everyone', max_length=20)),
                ('who_can_tag', models.CharField(choices=[('everyone', 'Everyone'), ('followers', 'Followers Only'), ('nobody', 'Nobody')], default='everyone', max_length=20)),
                ('show_online_status', models.BooleanField(default=True)),
                ('show_last_seen', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='privacy_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blocked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by', to=settings.AUTH_USER_MODEL)),
                ('blocker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocking', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('blocker', 'blocked'), name='unique_user_block'), models.CheckConstraint(condition=models.Q(('blocker', models.F('blocked')), _negated=True), name='prevent_self_block')],
            },
        ),
        migrations.CreateModel(
            name='UserMute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('muted', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muted_by', to=settings.AUTH_USER_MODEL)),
                ('muter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muting', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('muter', 'muted'), name='unique_user_mute'), models.CheckConstraint(condition=models.Q(('muter', models.F('muted')), _negated=True), name='prevent_self_mute')],
            },
        ),
        migrations.CreateModel(
            name='UserRestriction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('restricted', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restricted_by', to=settings.AUTH_USER_MODEL)),
                ('restrictor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restricting', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('restrictor', 'restricted'), name='unique_user_restriction'), models.CheckConstraint(condition=models.Q(('restrictor', models.F('restricted')), _negated=True), name='prevent_self_restriction')],
            },
        ),
    ]
