# Generated by Django 5.2.17 on 2026-08-22 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprivacysettings_userblock_usermute_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_verified',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
