# Generated by Django 5.2.17 on 2026-08-22 03:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('creator', 'Content Creator / Artist'), ('developer', 'Software Engineer / Tech Contributor'), ('business', 'Business / Organization'), ('public_figure', 'Public Figure / Journalist'), ('community_leader', 'Community Leader')], max_length=30)),
                ('reference_url', models.URLField(help_text='Public portfolio, GitHub, or official site', max_length=500)),
                ('reason', models.TextField(help_text='Brief explanation of work and credibility', max_length=1000)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved — Verified Badge Active'), ('rejected', 'Rejected'), ('revoked', 'Revoked')], db_index=True, default='pending', max_length=20)),
                ('review_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_verifications', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
