# Generated by Django 5.2.17 on 2026-08-22 02:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModerationQueueItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(max_length=30)),
                ('object_id', models.IntegerField()),
                ('flagged_reason', models.CharField(max_length=255)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('ai_provider', models.CharField(default='rule_based', max_length=50)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-confidence_score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModerationAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('target_summary', models.CharField(max_length=255)),
                ('reason', models.CharField(max_length=500)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('moderator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('post', 'Post'), ('comment', 'Comment'), ('user', 'User'), ('message', 'Message'), ('story', 'Story')], max_length=20)),
                ('target_id', models.IntegerField()),
                ('reason', models.CharField(choices=[('spam', 'Spam / Commercial advertising'), ('harassment', 'Harassment / Bullying'), ('hate', 'Hate speech or symbols'), ('violence', 'Violence or threat of violence'), ('scam', 'Scam / Fraudulent activity'), ('inappropriate', 'Inappropriate or explicit content'), ('other', 'Other issue')], max_length=30)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('reviewing', 'Under Review'), ('resolved', 'Resolved / Action Taken'), ('dismissed', 'Dismissed / No Violation')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_moderator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_reports', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_filed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='moderation__status_282342_idx'), models.Index(fields=['target_type', 'target_id'], name='moderation__target__dc17d8_idx')],
            },
        ),
    ]
