# Generated by Django 5.2.17 on 2026-08-22 02:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes_enabled', models.BooleanField(default=True)),
                ('comments_enabled', models.BooleanField(default=True)),
                ('follows_enabled', models.BooleanField(default=True)),
                ('mentions_enabled', models.BooleanField(default=True)),
                ('messages_enabled', models.BooleanField(default=True)),
                ('stories_enabled', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verb', models.CharField(choices=[('like', 'Liked your post'), ('comment', 'Commented on your post'), ('reply', 'Replied to your comment'), ('follow', 'Started following you'), ('mention', 'Mentioned you'), ('message', 'Sent you a message'), ('story_reaction', 'Reacted to your story'), ('bookmark', 'Saved your post')], max_length=30)),
                ('target_id', models.IntegerField(blank=True, null=True)),
                ('target_type', models.CharField(blank=True, max_length=50)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_generated', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', '-created_at'], name='notificatio_recipie_a972ce_idx'), models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_4e3567_idx')],
            },
        ),
    ]
